# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'om_abatartrucks',
    'version': '1.1',
    'category': 'Extra Tools',
    'summary': 'Abatar Trucks summary',
    'description': """
Aca va la desc
    """,
    'depends': [
        'base',
        'om_abatartrucks_add',
        'portal',
        'web',
        'mail',
        'calendar',
        'board',
        'website',
        'prt_report_attachment_preview',

    ],
    'qweb': ['static/src/xml/tree_view_button.xml'
             ],
    #'css': ['static/src/css/oe_new_custom_button2.css'],
    'data': [

        'security/seguridad.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/data.xml',
        'data/mail_template.xml',
        'data/sequence.xml',
        'reports/report.xml',
        'reports/report_ordenes.xml',
        'reports/report_ordenes_clientes.xml',
        'reports/report_ordenes_proveedores.xml',
        'reports/report_crm.xml',
        'reports/report_crm2.xml',
        'reports/report_resumenes.xml',
        'reports/report_caja.xml',
        'reports/report_clientes.xml',
        'reports/header.xml',
        'wizard/ventana_caja.xml',
        'views/booleana.xml',
        'views/cadena.xml',
        'views/caja.xml',
        'views/caja_tipo.xml',
        'views/calendario.xml',
        'views/clientes.xml',
        'views/clientes_gral.xml',
        'views/cotizador.xml',
        'views/cotizaciones.xml',
        'views/crm.xml',
        'views/dashboard.xml',
        'views/deudas.xml',
        'views/direcciones.xml',
        'views/dolar.xml',
        'views/dolar2.xml',
        'views/anotador.xml',
        'views/elementos.xml',
        'views/empleados.xml',
        'views/factura.xml',
        'views/institucional.xml',
        'views/indicadores.xml',
        'views/keyusuario.xml',
        'views/matemb.xml',
        'views/materiales.xml',
        'views/mensuales.xml',
        'views/pagos.xml',
        'views/ordenes.xml',
        'views/pagos_mensuales.xml',
        'views/pagos_empleados.xml',
        'views/productos.xml',
        'views/proveedores.xml',
        'views/resumenes.xml',
        'views/tarifas.xml',
        'views/tipo.xml',
        'views/menu.xml',
        'views/assets.xml',
        'views/template.xml',
    ],

    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False
}
